services:
  breedbase:
    volumes:
      - webdata:/home/production/volume
      - ./cxgn/sgn:/home/production/cxgn/sgn
      - ./sgn_local.conf:/home/production/cxgn/sgn/sgn_local.conf
    ports:
      - 8080:8080
    image: breedbase/breedbase:latest
    platform: linux/amd64
    # depends_on:
    #   - breedbase_db
    container_name: breedbase_web

  # breedbase_db:
  #   volumes:
  #     - dbdata:/var/lib/postgresql/data
  #   ports:
  #     - 5430:5432
  #   image: postgres:12.7
  #   platform: linux/amd64
  #   container_name: breedbase_db
  #   healthcheck:
  #     test: "pg_isready -U postgres -d $${POSTGRES_DB} || exit 1"
  #     interval: 10s

volumes:
  webdata:
  dbdata:
