services:
  breedbase:
    volumes:
      - type: bind
        source: ./sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
      - type: bind
        source: ./cxgn
        target: /home/production/cxgn
        # include .git dir that tracks all submodules in cxgn
      - type: bind
        source: .git
        target: /home/production/.git
    environment:
      MODE: 'DEVELOPMENT'
      PGDATABASE: breedbase
      PGHOST: breedbase_db
      PGPASSWORD: postgres
      PGUSER: postgres

  breedbase_db:
    environment:
      POSTGRES_DB: breedbase
      POSTGRES_PASSWORD: postgres
